PremiumizemeAPIKey: ""
SonarrURL: http://localhost:8989
SonarrAPIKey: ""
SonarrBlackholeDirectory: ""
SonarrDownloadsDirectory: ""
RadarrURL: http://localhost:7878
RadarrAPIKey: ""
RadarrBlackholeDirectory: ""
RadarrDownloadsDirectory: ""
bindIP: 0.0.0.0
bindPort: "8182"
